# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             all                                     trust
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256
host    openflake       openflake       10.0.0.0/8              scram-sha-256
host    openflake       openflake       172.16.0.0/12           scram-sha-256
host    openflake       openflake       192.168.0.0/24          scram-sha-256
host    openflake       openflake       192.168.1.0/24          scram-sha-256
