"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-18 16:47:35.453175

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_key",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("key_hash", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("user_sys_id", sa.String(length=32), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_api_key_key_hash"), "api_key", ["key_hash"], unique=True)
    op.create_table(
        "change_request",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("short_description", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=8), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=True),
        sa.Column("chg_model", sa.String(length=64), nullable=True),
        sa.Column("impact", sa.String(length=8), nullable=False),
        sa.Column("urgency", sa.String(length=8), nullable=False),
        sa.Column("priority", sa.String(length=8), nullable=False),
        sa.Column("risk", sa.String(length=8), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("requested_by", sa.String(length=32), nullable=True),
        sa.Column("assigned_to", sa.String(length=32), nullable=True),
        sa.Column("assignment_group", sa.String(length=32), nullable=True),
        sa.Column("on_hold", sa.String(length=8), nullable=False),
        sa.Column("on_hold_reason", sa.String(length=8), nullable=True),
        sa.Column("close_code", sa.String(length=128), nullable=True),
        sa.Column("close_notes", sa.Text(), nullable=True),
        sa.Column("std_change_producer_version", sa.String(length=32), nullable=True),
        sa.Column("cmdb_ci", sa.String(length=32), nullable=True),
        sa.Column("start_date", sa.String(length=64), nullable=True),
        sa.Column("end_date", sa.String(length=64), nullable=True),
        sa.Column("work_start", sa.String(length=64), nullable=True),
        sa.Column("work_end", sa.String(length=64), nullable=True),
        sa.Column("justification", sa.Text(), nullable=True),
        sa.Column("implementation_plan", sa.Text(), nullable=True),
        sa.Column("backout_plan", sa.Text(), nullable=True),
        sa.Column("test_plan", sa.Text(), nullable=True),
        sa.Column("review_date", sa.String(length=64), nullable=True),
        sa.Column("approval", sa.String(length=64), nullable=True),
        sa.Column("sys_class_name", sa.String(length=64), nullable=False),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("owner", sa.String(length=32), nullable=True),
        sa.Column("owner_group", sa.String(length=32), nullable=True),
        sa.Column("active", sa.String(length=8), nullable=False),
        sa.Column("work_notes", sa.Text(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("opened_at", sa.String(length=64), nullable=True),
        sa.Column("closed_at", sa.String(length=64), nullable=True),
        sa.Column("resolved_at", sa.String(length=64), nullable=True),
        sa.Column("due_date", sa.String(length=64), nullable=True),
        sa.Column("business_service", sa.String(length=32), nullable=True),
        sa.Column("escalation", sa.String(length=8), nullable=True),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_change_request_number"), "change_request", ["number"], unique=True)
    op.create_index(op.f("ix_change_request_owner"), "change_request", ["owner"], unique=False)
    op.create_index(
        op.f("ix_change_request_owner_group"), "change_request", ["owner_group"], unique=False
    )
    op.create_table(
        "cmdb_ci",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("sys_class_name", sa.String(length=128), nullable=False),
        sa.Column("sys_class_path", sa.String(length=512), nullable=True),
        sa.Column("host_name", sa.String(length=256), nullable=True),
        sa.Column("fqdn", sa.String(length=256), nullable=True),
        sa.Column("short_description", sa.String(length=512), nullable=True),
        sa.Column("asset_tag", sa.String(length=128), nullable=True),
        sa.Column("serial_number", sa.String(length=128), nullable=True),
        sa.Column("install_status", sa.String(length=8), nullable=True),
        sa.Column("operational_status", sa.String(length=8), nullable=True),
        sa.Column("classification", sa.String(length=128), nullable=True),
        sa.Column("environment", sa.String(length=64), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("mac_address", sa.String(length=64), nullable=True),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("vendor", sa.String(length=128), nullable=True),
        sa.Column("os", sa.String(length=128), nullable=True),
        sa.Column("os_version", sa.String(length=128), nullable=True),
        sa.Column("assigned_to", sa.String(length=32), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("owner", sa.String(length=32), nullable=True),
        sa.Column("owner_group", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_cmdb_ci_name"), "cmdb_ci", ["name"], unique=False)
    op.create_index(op.f("ix_cmdb_ci_owner"), "cmdb_ci", ["owner"], unique=False)
    op.create_index(op.f("ix_cmdb_ci_owner_group"), "cmdb_ci", ["owner_group"], unique=False)
    op.create_index(op.f("ix_cmdb_ci_sys_class_name"), "cmdb_ci", ["sys_class_name"], unique=False)
    op.create_table(
        "cmdb_rel_type",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("sys_name", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_cmdb_rel_type_sys_name"), "cmdb_rel_type", ["sys_name"], unique=True)
    op.create_table(
        "incident",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("short_description", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=8), nullable=False),
        sa.Column("impact", sa.String(length=8), nullable=False),
        sa.Column("urgency", sa.String(length=8), nullable=False),
        sa.Column("priority", sa.String(length=8), nullable=False),
        sa.Column("caller_id", sa.String(length=32), nullable=True),
        sa.Column("assigned_to", sa.String(length=32), nullable=True),
        sa.Column("assignment_group", sa.String(length=32), nullable=True),
        sa.Column("hold_reason", sa.String(length=8), nullable=True),
        sa.Column("close_code", sa.String(length=128), nullable=True),
        sa.Column("close_notes", sa.Text(), nullable=True),
        sa.Column("contact_type", sa.String(length=64), nullable=True),
        sa.Column("notify", sa.String(length=8), nullable=True),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("subcategory", sa.String(length=128), nullable=True),
        sa.Column("cmdb_ci", sa.String(length=32), nullable=True),
        sa.Column("opened_by", sa.String(length=32), nullable=True),
        sa.Column("resolved_by", sa.String(length=32), nullable=True),
        sa.Column("closed_by", sa.String(length=32), nullable=True),
        sa.Column("parent_incident", sa.String(length=32), nullable=True),
        sa.Column("sys_class_name", sa.String(length=64), nullable=False),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("owner", sa.String(length=32), nullable=True),
        sa.Column("owner_group", sa.String(length=32), nullable=True),
        sa.Column("active", sa.String(length=8), nullable=False),
        sa.Column("work_notes", sa.Text(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("opened_at", sa.String(length=64), nullable=True),
        sa.Column("closed_at", sa.String(length=64), nullable=True),
        sa.Column("resolved_at", sa.String(length=64), nullable=True),
        sa.Column("due_date", sa.String(length=64), nullable=True),
        sa.Column("business_service", sa.String(length=32), nullable=True),
        sa.Column("escalation", sa.String(length=8), nullable=True),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_incident_number"), "incident", ["number"], unique=True)
    op.create_index(op.f("ix_incident_owner"), "incident", ["owner"], unique=False)
    op.create_index(op.f("ix_incident_owner_group"), "incident", ["owner_group"], unique=False)
    op.create_table(
        "number_sequence",
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("prefix"),
    )
    op.create_table(
        "oauth_client",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("client_id", sa.String(length=128), nullable=False),
        sa.Column("client_secret", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_oauth_client_client_id"), "oauth_client", ["client_id"], unique=True)
    op.create_table(
        "oauth_token",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("access_token", sa.String(length=512), nullable=False),
        sa.Column("refresh_token", sa.String(length=512), nullable=True),
        sa.Column("client_id", sa.String(length=128), nullable=True),
        sa.Column("user_sys_id", sa.String(length=32), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("token_type", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("sys_id"),
        sa.UniqueConstraint("refresh_token"),
    )
    op.create_index(
        op.f("ix_oauth_token_access_token"), "oauth_token", ["access_token"], unique=True
    )
    op.create_table(
        "problem",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("short_description", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=8), nullable=False),
        sa.Column("impact", sa.String(length=8), nullable=False),
        sa.Column("urgency", sa.String(length=8), nullable=False),
        sa.Column("priority", sa.String(length=8), nullable=False),
        sa.Column("assigned_to", sa.String(length=32), nullable=True),
        sa.Column("assignment_group", sa.String(length=32), nullable=True),
        sa.Column("resolution_code", sa.String(length=128), nullable=True),
        sa.Column("cause_notes", sa.Text(), nullable=True),
        sa.Column("fix_notes", sa.Text(), nullable=True),
        sa.Column("close_notes", sa.Text(), nullable=True),
        sa.Column("duplicate_of", sa.String(length=32), nullable=True),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("subcategory", sa.String(length=128), nullable=True),
        sa.Column("cmdb_ci", sa.String(length=32), nullable=True),
        sa.Column("first_reported_by_task", sa.String(length=32), nullable=True),
        sa.Column("sys_class_name", sa.String(length=64), nullable=False),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("owner", sa.String(length=32), nullable=True),
        sa.Column("owner_group", sa.String(length=32), nullable=True),
        sa.Column("active", sa.String(length=8), nullable=False),
        sa.Column("work_notes", sa.Text(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("opened_at", sa.String(length=64), nullable=True),
        sa.Column("closed_at", sa.String(length=64), nullable=True),
        sa.Column("resolved_at", sa.String(length=64), nullable=True),
        sa.Column("due_date", sa.String(length=64), nullable=True),
        sa.Column("business_service", sa.String(length=32), nullable=True),
        sa.Column("escalation", sa.String(length=8), nullable=True),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_problem_number"), "problem", ["number"], unique=True)
    op.create_index(op.f("ix_problem_owner"), "problem", ["owner"], unique=False)
    op.create_index(op.f("ix_problem_owner_group"), "problem", ["owner_group"], unique=False)
    op.create_table(
        "record_access_grant",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("table_name", sa.String(length=128), nullable=False),
        sa.Column("record_sys_id", sa.String(length=32), nullable=False),
        sa.Column("user_sys_id", sa.String(length=32), nullable=True),
        sa.Column("group_sys_id", sa.String(length=32), nullable=True),
        sa.Column("access_level", sa.String(length=16), nullable=False),
        sa.Column("granted_by", sa.String(length=32), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(
        op.f("ix_record_access_grant_group_sys_id"),
        "record_access_grant",
        ["group_sys_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_record_access_grant_record_sys_id"),
        "record_access_grant",
        ["record_sys_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_record_access_grant_table_name"),
        "record_access_grant",
        ["table_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_record_access_grant_user_sys_id"),
        "record_access_grant",
        ["user_sys_id"],
        unique=False,
    )
    op.create_table(
        "sc_cat_item",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("catalog_sys_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("short_description", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("price", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("subcategory", sa.String(length=128), nullable=True),
        sa.Column("fulfillment_group", sa.String(length=32), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("icon", sa.String(length=256), nullable=True),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(
        op.f("ix_sc_cat_item_catalog_sys_id"), "sc_cat_item", ["catalog_sys_id"], unique=False
    )
    op.create_index(
        op.f("ix_sc_cat_item_fulfillment_group"),
        "sc_cat_item",
        ["fulfillment_group"],
        unique=False,
    )
    op.create_index(op.f("ix_sc_cat_item_name"), "sc_cat_item", ["name"], unique=False)
    op.create_table(
        "sc_request",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("short_description", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=8), nullable=False),
        sa.Column("request_state", sa.String(length=64), nullable=True),
        sa.Column("priority", sa.String(length=8), nullable=True),
        sa.Column("urgency", sa.String(length=8), nullable=True),
        sa.Column("impact", sa.String(length=8), nullable=True),
        sa.Column("requested_for", sa.String(length=32), nullable=True),
        sa.Column("requested_by", sa.String(length=32), nullable=True),
        sa.Column("assignment_group", sa.String(length=32), nullable=True),
        sa.Column("assigned_to", sa.String(length=32), nullable=True),
        sa.Column("opened_by", sa.String(length=32), nullable=True),
        sa.Column("cmdb_ci", sa.String(length=32), nullable=True),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("subcategory", sa.String(length=128), nullable=True),
        sa.Column("delivery_plan", sa.Text(), nullable=True),
        sa.Column("delivery_task", sa.String(length=256), nullable=True),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("approval", sa.String(length=64), nullable=True),
        sa.Column("sys_class_name", sa.String(length=64), nullable=False),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("owner", sa.String(length=32), nullable=True),
        sa.Column("owner_group", sa.String(length=32), nullable=True),
        sa.Column("active", sa.String(length=8), nullable=False),
        sa.Column("work_notes", sa.Text(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("opened_at", sa.String(length=64), nullable=True),
        sa.Column("closed_at", sa.String(length=64), nullable=True),
        sa.Column("resolved_at", sa.String(length=64), nullable=True),
        sa.Column("due_date", sa.String(length=64), nullable=True),
        sa.Column("business_service", sa.String(length=32), nullable=True),
        sa.Column("escalation", sa.String(length=8), nullable=True),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_sc_request_number"), "sc_request", ["number"], unique=True)
    op.create_index(op.f("ix_sc_request_owner"), "sc_request", ["owner"], unique=False)
    op.create_index(op.f("ix_sc_request_owner_group"), "sc_request", ["owner_group"], unique=False)
    op.create_table(
        "sc_webhook",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("method", sa.String(length=8), nullable=False),
        sa.Column(
            "headers", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("secret", sa.String(length=256), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_sc_webhook_name"), "sc_webhook", ["name"], unique=False)
    op.create_table(
        "service_catalog",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_table(
        "std_change_producer_version",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("short_description", sa.String(length=512), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.String(length=8), nullable=False),
        sa.Column("template", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.PrimaryKeyConstraint("sys_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "sys_attachment",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("table_name", sa.String(length=128), nullable=False),
        sa.Column("table_sys_id", sa.String(length=32), nullable=False),
        sa.Column("file_name", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.String(length=1024), nullable=False),
        sa.Column("hash", sa.String(length=256), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=True),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(
        op.f("ix_sys_attachment_table_sys_id"), "sys_attachment", ["table_sys_id"], unique=False
    )
    op.create_table(
        "sys_audit",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("table_name", sa.String(length=128), nullable=False),
        sa.Column("record_sys_id", sa.String(length=32), nullable=False),
        sa.Column("batch_id", sa.String(length=32), nullable=False),
        sa.Column("field_name", sa.String(length=128), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("user", sa.String(length=128), nullable=True),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_sys_audit_batch_id"), "sys_audit", ["batch_id"], unique=False)
    op.create_index(
        op.f("ix_sys_audit_record_sys_id"), "sys_audit", ["record_sys_id"], unique=False
    )
    op.create_index(op.f("ix_sys_audit_table_name"), "sys_audit", ["table_name"], unique=False)
    op.create_table(
        "sys_comment",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("table_name", sa.String(length=128), nullable=False),
        sa.Column("record_sys_id", sa.String(length=32), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(
        op.f("ix_sys_comment_record_sys_id"), "sys_comment", ["record_sys_id"], unique=False
    )
    op.create_index(op.f("ix_sys_comment_table_name"), "sys_comment", ["table_name"], unique=False)
    op.create_table(
        "sys_db_object",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("label", sa.String(length=256), nullable=False),
        sa.Column("super_class", sa.String(length=128), nullable=True),
        sa.Column("is_logical", sa.Boolean(), nullable=False),
        sa.Column("is_extendable", sa.Boolean(), nullable=False),
        sa.Column("number_prefix", sa.String(length=16), nullable=True),
        sa.Column("storage_type", sa.String(length=16), nullable=False),
        sa.Column("base_table", sa.String(length=128), nullable=True),
        sa.Column("user_defined", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["super_class"], ["sys_db_object.name"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sys_id"),
        sa.UniqueConstraint("name", name="uq_sys_db_object_name"),
    )
    op.create_index(op.f("ix_sys_db_object_name"), "sys_db_object", ["name"], unique=False)
    op.create_index(
        op.f("ix_sys_db_object_super_class"), "sys_db_object", ["super_class"], unique=False
    )
    op.create_table(
        "sys_group_role",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("group_sys_id", sa.String(length=32), nullable=False),
        sa.Column("role_sys_id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(
        op.f("ix_sys_group_role_group_sys_id"), "sys_group_role", ["group_sys_id"], unique=False
    )
    op.create_index(
        op.f("ix_sys_group_role_role_sys_id"), "sys_group_role", ["role_sys_id"], unique=False
    )
    op.create_table(
        "sys_role",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("suffix", sa.String(length=64), nullable=True),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_sys_role_name"), "sys_role", ["name"], unique=True)
    op.create_table(
        "sys_secret",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_sys_secret_name"), "sys_secret", ["name"], unique=True)
    op.create_table(
        "sys_user",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("user_name", sa.String(length=128), nullable=False),
        sa.Column("user_password", sa.String(length=256), nullable=False),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("mobile_phone", sa.String(length=64), nullable=True),
        sa.Column("department", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("location", sa.String(length=256), nullable=True),
        sa.Column("company", sa.String(length=128), nullable=True),
        sa.Column("manager", sa.String(length=32), nullable=True),
        sa.Column("time_zone", sa.String(length=64), nullable=True),
        sa.Column("vip", sa.String(length=8), nullable=True),
        sa.Column("employee_number", sa.String(length=64), nullable=True),
        sa.Column("active", sa.String(length=8), nullable=False),
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_sys_user_user_name"), "sys_user", ["user_name"], unique=True)
    op.create_table(
        "sys_user_grmember",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("user_sys_id", sa.String(length=32), nullable=False),
        sa.Column("group_sys_id", sa.String(length=32), nullable=False),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(
        op.f("ix_sys_user_grmember_group_sys_id"),
        "sys_user_grmember",
        ["group_sys_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sys_user_grmember_user_sys_id"),
        "sys_user_grmember",
        ["user_sys_id"],
        unique=False,
    )
    op.create_table(
        "sys_user_group",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=True),
        sa.Column("active", sa.String(length=8), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("manager", sa.String(length=32), nullable=True),
        sa.Column("parent", sa.String(length=32), nullable=True),
        sa.Column("owner", sa.String(length=32), nullable=True),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_sys_user_group_name"), "sys_user_group", ["name"], unique=True)
    op.create_index(op.f("ix_sys_user_group_owner"), "sys_user_group", ["owner"], unique=False)
    op.create_table(
        "change_task",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("short_description", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=8), nullable=False),
        sa.Column("change_request", sa.String(length=32), nullable=True),
        sa.Column("change_task_type", sa.String(length=64), nullable=True),
        sa.Column("cmdb_ci", sa.String(length=32), nullable=True),
        sa.Column("assigned_to", sa.String(length=32), nullable=True),
        sa.Column("assignment_group", sa.String(length=32), nullable=True),
        sa.Column("priority", sa.String(length=8), nullable=True),
        sa.Column("impact", sa.String(length=8), nullable=True),
        sa.Column("urgency", sa.String(length=8), nullable=True),
        sa.Column("on_hold", sa.String(length=8), nullable=False),
        sa.Column("hold_reason", sa.String(length=8), nullable=True),
        sa.Column("close_code", sa.String(length=128), nullable=True),
        sa.Column("close_notes", sa.Text(), nullable=True),
        sa.Column("planned_start_date", sa.String(length=64), nullable=True),
        sa.Column("planned_end_date", sa.String(length=64), nullable=True),
        sa.Column("sys_class_name", sa.String(length=64), nullable=False),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("owner", sa.String(length=32), nullable=True),
        sa.Column("owner_group", sa.String(length=32), nullable=True),
        sa.Column("active", sa.String(length=8), nullable=False),
        sa.Column("work_notes", sa.Text(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("opened_at", sa.String(length=64), nullable=True),
        sa.Column("closed_at", sa.String(length=64), nullable=True),
        sa.Column("resolved_at", sa.String(length=64), nullable=True),
        sa.Column("due_date", sa.String(length=64), nullable=True),
        sa.Column("business_service", sa.String(length=32), nullable=True),
        sa.Column("escalation", sa.String(length=8), nullable=True),
        sa.ForeignKeyConstraint(["change_request"], ["change_request.sys_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_change_task_number"), "change_task", ["number"], unique=True)
    op.create_index(op.f("ix_change_task_owner"), "change_task", ["owner"], unique=False)
    op.create_index(
        op.f("ix_change_task_owner_group"), "change_task", ["owner_group"], unique=False
    )
    op.create_table(
        "cmdb_rel_ci",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("parent", sa.String(length=32), nullable=False),
        sa.Column("child", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("connection_strength", sa.String(length=64), nullable=True),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["child"], ["cmdb_ci.sys_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent"], ["cmdb_ci.sys_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_cmdb_rel_ci_child"), "cmdb_rel_ci", ["child"], unique=False)
    op.create_index(op.f("ix_cmdb_rel_ci_parent"), "cmdb_rel_ci", ["parent"], unique=False)
    op.create_table(
        "item_option_new",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("cat_item", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("question_text", sa.String(length=512), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("mandatory", sa.Boolean(), nullable=False),
        sa.Column("default_value", sa.String(length=512), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("reference_table", sa.String(length=128), nullable=True),
        sa.Column("reference_filter", sa.Text(), nullable=True),
        sa.Column("reference_display_field", sa.String(length=128), nullable=True),
        sa.Column(
            "choice_list",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("help_text", sa.Text(), nullable=True),
        sa.Column("read_only", sa.Boolean(), nullable=False),
        sa.Column("hidden", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["cat_item"], ["sc_cat_item.sys_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(
        op.f("ix_item_option_new_cat_item"), "item_option_new", ["cat_item"], unique=False
    )
    op.create_index(op.f("ix_item_option_new_name"), "item_option_new", ["name"], unique=False)
    op.create_table(
        "problem_task",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("short_description", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=8), nullable=False),
        sa.Column("problem", sa.String(length=32), nullable=True),
        sa.Column("problem_task_type", sa.String(length=64), nullable=True),
        sa.Column("cmdb_ci", sa.String(length=32), nullable=True),
        sa.Column("assigned_to", sa.String(length=32), nullable=True),
        sa.Column("assignment_group", sa.String(length=32), nullable=True),
        sa.Column("priority", sa.String(length=8), nullable=False),
        sa.Column("impact", sa.String(length=8), nullable=True),
        sa.Column("urgency", sa.String(length=8), nullable=True),
        sa.Column("close_code", sa.String(length=128), nullable=True),
        sa.Column("close_notes", sa.Text(), nullable=True),
        sa.Column("sys_class_name", sa.String(length=64), nullable=False),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("owner", sa.String(length=32), nullable=True),
        sa.Column("owner_group", sa.String(length=32), nullable=True),
        sa.Column("active", sa.String(length=8), nullable=False),
        sa.Column("work_notes", sa.Text(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("opened_at", sa.String(length=64), nullable=True),
        sa.Column("closed_at", sa.String(length=64), nullable=True),
        sa.Column("resolved_at", sa.String(length=64), nullable=True),
        sa.Column("due_date", sa.String(length=64), nullable=True),
        sa.Column("business_service", sa.String(length=32), nullable=True),
        sa.Column("escalation", sa.String(length=8), nullable=True),
        sa.ForeignKeyConstraint(["problem"], ["problem.sys_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_problem_task_number"), "problem_task", ["number"], unique=True)
    op.create_index(op.f("ix_problem_task_owner"), "problem_task", ["owner"], unique=False)
    op.create_index(
        op.f("ix_problem_task_owner_group"), "problem_task", ["owner_group"], unique=False
    )
    op.create_table(
        "sc_cat_item_webhook",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("cat_item", sa.String(length=32), nullable=False),
        sa.Column("webhook", sa.String(length=32), nullable=False),
        sa.Column("payload_template", sa.Text(), nullable=True),
        sa.Column("trigger_on", sa.String(length=32), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["cat_item"], ["sc_cat_item.sys_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["webhook"], ["sc_webhook.sys_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(
        op.f("ix_sc_cat_item_webhook_cat_item"), "sc_cat_item_webhook", ["cat_item"], unique=False
    )
    op.create_index(
        op.f("ix_sc_cat_item_webhook_webhook"), "sc_cat_item_webhook", ["webhook"], unique=False
    )
    op.create_table(
        "sc_req_item",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("request", sa.String(length=32), nullable=True),
        sa.Column("cat_item", sa.String(length=32), nullable=True),
        sa.Column("state", sa.String(length=8), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.String(length=32), nullable=True),
        sa.Column("short_description", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("assigned_to", sa.String(length=32), nullable=True),
        sa.Column("assignment_group", sa.String(length=32), nullable=True),
        sa.Column("cmdb_ci", sa.String(length=32), nullable=True),
        sa.Column("approval", sa.String(length=64), nullable=True),
        sa.Column("priority", sa.String(length=8), nullable=True),
        sa.Column("urgency", sa.String(length=8), nullable=True),
        sa.Column("impact", sa.String(length=8), nullable=True),
        sa.Column("opened_by", sa.String(length=32), nullable=True),
        sa.Column("sys_class_name", sa.String(length=64), nullable=False),
        sa.Column("requested_for", sa.String(length=32), nullable=True),
        sa.Column("upon_approval", sa.String(length=32), nullable=True),
        sa.Column("upon_reject", sa.String(length=32), nullable=True),
        sa.Column("approval_set", sa.String(length=64), nullable=True),
        sa.Column("made_sla", sa.String(length=8), nullable=True),
        sa.Column("reassignment_count", sa.String(length=8), nullable=True),
        sa.Column("recurring_price", sa.String(length=32), nullable=True),
        sa.Column("backordered", sa.String(length=8), nullable=True),
        sa.Column("billable", sa.String(length=8), nullable=True),
        sa.Column("knowledge", sa.String(length=8), nullable=True),
        sa.Column("delivery_plan", sa.String(length=32), nullable=True),
        sa.Column("sys_domain", sa.String(length=64), nullable=True),
        sa.Column("sys_domain_path", sa.String(length=256), nullable=True),
        sa.Column("task_effective_number", sa.String(length=32), nullable=True),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("owner", sa.String(length=32), nullable=True),
        sa.Column("owner_group", sa.String(length=32), nullable=True),
        sa.Column("active", sa.String(length=8), nullable=False),
        sa.Column("work_notes", sa.Text(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("opened_at", sa.String(length=64), nullable=True),
        sa.Column("closed_at", sa.String(length=64), nullable=True),
        sa.Column("resolved_at", sa.String(length=64), nullable=True),
        sa.Column("due_date", sa.String(length=64), nullable=True),
        sa.Column("business_service", sa.String(length=32), nullable=True),
        sa.Column("escalation", sa.String(length=8), nullable=True),
        sa.ForeignKeyConstraint(["request"], ["sc_request.sys_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_sc_req_item_cat_item"), "sc_req_item", ["cat_item"], unique=False)
    op.create_index(op.f("ix_sc_req_item_number"), "sc_req_item", ["number"], unique=True)
    op.create_index(op.f("ix_sc_req_item_owner"), "sc_req_item", ["owner"], unique=False)
    op.create_index(
        op.f("ix_sc_req_item_owner_group"), "sc_req_item", ["owner_group"], unique=False
    )
    op.create_index(op.f("ix_sc_req_item_request"), "sc_req_item", ["request"], unique=False)
    op.create_table(
        "sc_task",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("short_description", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=8), nullable=False),
        sa.Column("request", sa.String(length=32), nullable=True),
        sa.Column("assigned_to", sa.String(length=32), nullable=True),
        sa.Column("assignment_group", sa.String(length=32), nullable=True),
        sa.Column("priority", sa.String(length=8), nullable=True),
        sa.Column("urgency", sa.String(length=8), nullable=True),
        sa.Column("impact", sa.String(length=8), nullable=True),
        sa.Column("cmdb_ci", sa.String(length=32), nullable=True),
        sa.Column("cat_item", sa.String(length=32), nullable=True),
        sa.Column("request_item", sa.String(length=32), nullable=True),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("approval", sa.String(length=64), nullable=True),
        sa.Column("sys_class_name", sa.String(length=64), nullable=False),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("owner", sa.String(length=32), nullable=True),
        sa.Column("owner_group", sa.String(length=32), nullable=True),
        sa.Column("active", sa.String(length=8), nullable=False),
        sa.Column("work_notes", sa.Text(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("opened_at", sa.String(length=64), nullable=True),
        sa.Column("closed_at", sa.String(length=64), nullable=True),
        sa.Column("resolved_at", sa.String(length=64), nullable=True),
        sa.Column("due_date", sa.String(length=64), nullable=True),
        sa.Column("business_service", sa.String(length=32), nullable=True),
        sa.Column("escalation", sa.String(length=8), nullable=True),
        sa.ForeignKeyConstraint(["request"], ["sc_request.sys_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(op.f("ix_sc_task_number"), "sc_task", ["number"], unique=True)
    op.create_index(op.f("ix_sc_task_owner"), "sc_task", ["owner"], unique=False)
    op.create_index(op.f("ix_sc_task_owner_group"), "sc_task", ["owner_group"], unique=False)
    op.create_table(
        "sc_webhook_log",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("webhook_id", sa.String(length=32), nullable=False),
        sa.Column("attachment_id", sa.String(length=32), nullable=True),
        sa.Column("sc_req_item", sa.String(length=32), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["webhook_id"], ["sc_webhook.sys_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(
        op.f("ix_sc_webhook_log_attachment_id"), "sc_webhook_log", ["attachment_id"], unique=False
    )
    op.create_index(
        op.f("ix_sc_webhook_log_sc_req_item"), "sc_webhook_log", ["sc_req_item"], unique=False
    )
    op.create_index(
        op.f("ix_sc_webhook_log_webhook_id"), "sc_webhook_log", ["webhook_id"], unique=False
    )
    op.create_table(
        "sys_dictionary",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("element", sa.String(length=128), nullable=False),
        sa.Column("column_label", sa.String(length=256), nullable=True),
        sa.Column("internal_type", sa.String(length=64), nullable=False),
        sa.Column("max_length", sa.Integer(), nullable=True),
        sa.Column("reference", sa.String(length=128), nullable=True),
        sa.Column("storage", sa.String(length=16), nullable=False),
        sa.Column("default_value", sa.String(length=512), nullable=True),
        sa.Column("mandatory", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("user_defined", sa.Boolean(), nullable=False),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["name"], ["sys_db_object.name"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sys_id"),
        sa.UniqueConstraint("name", "element"),
    )
    op.create_index(op.f("ix_sys_dictionary_name"), "sys_dictionary", ["name"], unique=False)
    op.create_table(
        "item_option_new_condition",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("variable", sa.String(length=32), nullable=False),
        sa.Column("condition_type", sa.String(length=32), nullable=False),
        sa.Column("depends_on", sa.String(length=32), nullable=False),
        sa.Column("operator", sa.String(length=16), nullable=False),
        sa.Column("value", sa.String(length=512), nullable=True),
        sa.Column("filter_override", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["depends_on"], ["item_option_new.sys_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["variable"], ["item_option_new.sys_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(
        op.f("ix_item_option_new_condition_depends_on"),
        "item_option_new_condition",
        ["depends_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_item_option_new_condition_variable"),
        "item_option_new_condition",
        ["variable"],
        unique=False,
    )
    op.create_table(
        "sc_item_option",
        sa.Column("sys_id", sa.String(length=32), nullable=False),
        sa.Column("item_option_new", sa.String(length=32), nullable=False),
        sa.Column("sc_req_item", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column(
            "other", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "sys_created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sys_updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sys_created_by", sa.String(length=128), nullable=True),
        sa.Column("sys_updated_by", sa.String(length=128), nullable=True),
        sa.Column("sys_mod_count", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["sc_req_item"], ["sc_req_item.sys_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sys_id"),
    )
    op.create_index(
        op.f("ix_sc_item_option_item_option_new"),
        "sc_item_option",
        ["item_option_new"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sc_item_option_sc_req_item"), "sc_item_option", ["sc_req_item"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sc_item_option_sc_req_item"), table_name="sc_item_option")
    op.drop_index(op.f("ix_sc_item_option_item_option_new"), table_name="sc_item_option")
    op.drop_table("sc_item_option")
    op.drop_index(
        op.f("ix_item_option_new_condition_variable"), table_name="item_option_new_condition"
    )
    op.drop_index(
        op.f("ix_item_option_new_condition_depends_on"), table_name="item_option_new_condition"
    )
    op.drop_table("item_option_new_condition")
    op.drop_index(op.f("ix_sys_dictionary_name"), table_name="sys_dictionary")
    op.drop_table("sys_dictionary")
    op.drop_index(op.f("ix_sc_webhook_log_webhook_id"), table_name="sc_webhook_log")
    op.drop_index(op.f("ix_sc_webhook_log_sc_req_item"), table_name="sc_webhook_log")
    op.drop_index(op.f("ix_sc_webhook_log_attachment_id"), table_name="sc_webhook_log")
    op.drop_table("sc_webhook_log")
    op.drop_index(op.f("ix_sc_task_owner_group"), table_name="sc_task")
    op.drop_index(op.f("ix_sc_task_owner"), table_name="sc_task")
    op.drop_index(op.f("ix_sc_task_number"), table_name="sc_task")
    op.drop_table("sc_task")
    op.drop_index(op.f("ix_sc_req_item_request"), table_name="sc_req_item")
    op.drop_index(op.f("ix_sc_req_item_owner_group"), table_name="sc_req_item")
    op.drop_index(op.f("ix_sc_req_item_owner"), table_name="sc_req_item")
    op.drop_index(op.f("ix_sc_req_item_number"), table_name="sc_req_item")
    op.drop_index(op.f("ix_sc_req_item_cat_item"), table_name="sc_req_item")
    op.drop_table("sc_req_item")
    op.drop_index(op.f("ix_sc_cat_item_webhook_webhook"), table_name="sc_cat_item_webhook")
    op.drop_index(op.f("ix_sc_cat_item_webhook_cat_item"), table_name="sc_cat_item_webhook")
    op.drop_table("sc_cat_item_webhook")
    op.drop_index(op.f("ix_problem_task_owner_group"), table_name="problem_task")
    op.drop_index(op.f("ix_problem_task_owner"), table_name="problem_task")
    op.drop_index(op.f("ix_problem_task_number"), table_name="problem_task")
    op.drop_table("problem_task")
    op.drop_index(op.f("ix_item_option_new_name"), table_name="item_option_new")
    op.drop_index(op.f("ix_item_option_new_cat_item"), table_name="item_option_new")
    op.drop_table("item_option_new")
    op.drop_index(op.f("ix_cmdb_rel_ci_parent"), table_name="cmdb_rel_ci")
    op.drop_index(op.f("ix_cmdb_rel_ci_child"), table_name="cmdb_rel_ci")
    op.drop_table("cmdb_rel_ci")
    op.drop_index(op.f("ix_change_task_owner_group"), table_name="change_task")
    op.drop_index(op.f("ix_change_task_owner"), table_name="change_task")
    op.drop_index(op.f("ix_change_task_number"), table_name="change_task")
    op.drop_table("change_task")
    op.drop_index(op.f("ix_sys_user_group_owner"), table_name="sys_user_group")
    op.drop_index(op.f("ix_sys_user_group_name"), table_name="sys_user_group")
    op.drop_table("sys_user_group")
    op.drop_index(op.f("ix_sys_user_grmember_user_sys_id"), table_name="sys_user_grmember")
    op.drop_index(op.f("ix_sys_user_grmember_group_sys_id"), table_name="sys_user_grmember")
    op.drop_table("sys_user_grmember")
    op.drop_index(op.f("ix_sys_user_user_name"), table_name="sys_user")
    op.drop_table("sys_user")
    op.drop_index(op.f("ix_sys_secret_name"), table_name="sys_secret")
    op.drop_table("sys_secret")
    op.drop_index(op.f("ix_sys_role_name"), table_name="sys_role")
    op.drop_table("sys_role")
    op.drop_index(op.f("ix_sys_group_role_role_sys_id"), table_name="sys_group_role")
    op.drop_index(op.f("ix_sys_group_role_group_sys_id"), table_name="sys_group_role")
    op.drop_table("sys_group_role")
    op.drop_index(op.f("ix_sys_db_object_super_class"), table_name="sys_db_object")
    op.drop_index(op.f("ix_sys_db_object_name"), table_name="sys_db_object")
    op.drop_table("sys_db_object")
    op.drop_index(op.f("ix_sys_comment_table_name"), table_name="sys_comment")
    op.drop_index(op.f("ix_sys_comment_record_sys_id"), table_name="sys_comment")
    op.drop_table("sys_comment")
    op.drop_index(op.f("ix_sys_audit_table_name"), table_name="sys_audit")
    op.drop_index(op.f("ix_sys_audit_record_sys_id"), table_name="sys_audit")
    op.drop_index(op.f("ix_sys_audit_batch_id"), table_name="sys_audit")
    op.drop_table("sys_audit")
    op.drop_index(op.f("ix_sys_attachment_table_sys_id"), table_name="sys_attachment")
    op.drop_table("sys_attachment")
    op.drop_table("std_change_producer_version")
    op.drop_table("service_catalog")
    op.drop_index(op.f("ix_sc_webhook_name"), table_name="sc_webhook")
    op.drop_table("sc_webhook")
    op.drop_index(op.f("ix_sc_request_owner_group"), table_name="sc_request")
    op.drop_index(op.f("ix_sc_request_owner"), table_name="sc_request")
    op.drop_index(op.f("ix_sc_request_number"), table_name="sc_request")
    op.drop_table("sc_request")
    op.drop_index(op.f("ix_sc_cat_item_name"), table_name="sc_cat_item")
    op.drop_index(op.f("ix_sc_cat_item_fulfillment_group"), table_name="sc_cat_item")
    op.drop_index(op.f("ix_sc_cat_item_catalog_sys_id"), table_name="sc_cat_item")
    op.drop_table("sc_cat_item")
    op.drop_index(op.f("ix_record_access_grant_user_sys_id"), table_name="record_access_grant")
    op.drop_index(op.f("ix_record_access_grant_table_name"), table_name="record_access_grant")
    op.drop_index(op.f("ix_record_access_grant_record_sys_id"), table_name="record_access_grant")
    op.drop_index(op.f("ix_record_access_grant_group_sys_id"), table_name="record_access_grant")
    op.drop_table("record_access_grant")
    op.drop_index(op.f("ix_problem_owner_group"), table_name="problem")
    op.drop_index(op.f("ix_problem_owner"), table_name="problem")
    op.drop_index(op.f("ix_problem_number"), table_name="problem")
    op.drop_table("problem")
    op.drop_index(op.f("ix_oauth_token_access_token"), table_name="oauth_token")
    op.drop_table("oauth_token")
    op.drop_index(op.f("ix_oauth_client_client_id"), table_name="oauth_client")
    op.drop_table("oauth_client")
    op.drop_table("number_sequence")
    op.drop_index(op.f("ix_incident_owner_group"), table_name="incident")
    op.drop_index(op.f("ix_incident_owner"), table_name="incident")
    op.drop_index(op.f("ix_incident_number"), table_name="incident")
    op.drop_table("incident")
    op.drop_index(op.f("ix_cmdb_rel_type_sys_name"), table_name="cmdb_rel_type")
    op.drop_table("cmdb_rel_type")
    op.drop_index(op.f("ix_cmdb_ci_sys_class_name"), table_name="cmdb_ci")
    op.drop_index(op.f("ix_cmdb_ci_owner_group"), table_name="cmdb_ci")
    op.drop_index(op.f("ix_cmdb_ci_owner"), table_name="cmdb_ci")
    op.drop_index(op.f("ix_cmdb_ci_name"), table_name="cmdb_ci")
    op.drop_table("cmdb_ci")
    op.drop_index(op.f("ix_change_request_owner_group"), table_name="change_request")
    op.drop_index(op.f("ix_change_request_owner"), table_name="change_request")
    op.drop_index(op.f("ix_change_request_number"), table_name="change_request")
    op.drop_table("change_request")
    op.drop_index(op.f("ix_api_key_key_hash"), table_name="api_key")
    op.drop_table("api_key")
    # ### end Alembic commands ###
