"""Incremental column additions for ServiceNow-compatible schema fields."""

# (table, column, sql_type)
SCHEMA_COLUMN_MIGRATIONS: list[tuple[str, str, str]] = [
    # cmdb_ci — Ansible inventory / configuration_item module
    ("cmdb_ci", "host_name", "VARCHAR(256)"),
    ("cmdb_ci", "fqdn", "VARCHAR(256)"),
    ("cmdb_ci", "classification", "VARCHAR(128)"),
    ("cmdb_ci", "vendor", "VARCHAR(128)"),
    ("cmdb_ci", "os", "VARCHAR(128)"),
    ("cmdb_ci", "os_version", "VARCHAR(128)"),
    ("cmdb_ci", "manufacturer", "VARCHAR(128)"),
    ("cmdb_ci", "model_number", "VARCHAR(256)"),
    ("cmdb_ci", "location", "VARCHAR(256)"),
    ("cmdb_ci", "company", "VARCHAR(128)"),
    ("cmdb_ci", "support_group", "VARCHAR(32)"),
    ("cmdb_ci", "managed_by", "VARCHAR(32)"),
    ("cmdb_ci", "assignment_group", "VARCHAR(32)"),
    ("cmdb_ci", "discovered", "VARCHAR(64)"),
    ("cmdb_ci", "last_discovered", "VARCHAR(64)"),
    # incident — task + incident fields
    ("incident", "active", "VARCHAR(8)"),
    ("incident", "work_notes", "TEXT"),
    ("incident", "comments", "TEXT"),
    ("incident", "opened_at", "VARCHAR(64)"),
    ("incident", "closed_at", "VARCHAR(64)"),
    ("incident", "resolved_at", "VARCHAR(64)"),
    ("incident", "due_date", "VARCHAR(64)"),
    ("incident", "cmdb_ci", "VARCHAR(32)"),
    ("incident", "business_service", "VARCHAR(32)"),
    ("incident", "escalation", "VARCHAR(8)"),
    ("incident", "contact_type", "VARCHAR(64)"),
    ("incident", "notify", "VARCHAR(8)"),
    ("incident", "category", "VARCHAR(128)"),
    ("incident", "subcategory", "VARCHAR(128)"),
    ("incident", "opened_by", "VARCHAR(32)"),
    ("incident", "resolved_by", "VARCHAR(32)"),
    ("incident", "closed_by", "VARCHAR(32)"),
    ("incident", "parent_incident", "VARCHAR(32)"),
    # problem
    ("problem", "active", "VARCHAR(8)"),
    ("problem", "work_notes", "TEXT"),
    ("problem", "comments", "TEXT"),
    ("problem", "opened_at", "VARCHAR(64)"),
    ("problem", "closed_at", "VARCHAR(64)"),
    ("problem", "resolved_at", "VARCHAR(64)"),
    ("problem", "due_date", "VARCHAR(64)"),
    ("problem", "cmdb_ci", "VARCHAR(32)"),
    ("problem", "business_service", "VARCHAR(32)"),
    ("problem", "escalation", "VARCHAR(8)"),
    ("problem", "category", "VARCHAR(128)"),
    ("problem", "subcategory", "VARCHAR(128)"),
    ("problem", "first_reported_by_task", "VARCHAR(32)"),
    # problem_task
    ("problem_task", "active", "VARCHAR(8)"),
    ("problem_task", "work_notes", "TEXT"),
    ("problem_task", "comments", "TEXT"),
    ("problem_task", "opened_at", "VARCHAR(64)"),
    ("problem_task", "closed_at", "VARCHAR(64)"),
    ("problem_task", "resolved_at", "VARCHAR(64)"),
    ("problem_task", "due_date", "VARCHAR(64)"),
    ("problem_task", "business_service", "VARCHAR(32)"),
    ("problem_task", "escalation", "VARCHAR(8)"),
    ("problem_task", "impact", "VARCHAR(8)"),
    ("problem_task", "urgency", "VARCHAR(8)"),
    ("problem_task", "close_code", "VARCHAR(128)"),
    ("problem_task", "close_notes", "TEXT"),
    # change_request
    ("change_request", "active", "VARCHAR(8)"),
    ("change_request", "work_notes", "TEXT"),
    ("change_request", "comments", "TEXT"),
    ("change_request", "opened_at", "VARCHAR(64)"),
    ("change_request", "closed_at", "VARCHAR(64)"),
    ("change_request", "resolved_at", "VARCHAR(64)"),
    ("change_request", "due_date", "VARCHAR(64)"),
    ("change_request", "cmdb_ci", "VARCHAR(32)"),
    ("change_request", "business_service", "VARCHAR(32)"),
    ("change_request", "escalation", "VARCHAR(8)"),
    ("change_request", "start_date", "VARCHAR(64)"),
    ("change_request", "end_date", "VARCHAR(64)"),
    ("change_request", "work_start", "VARCHAR(64)"),
    ("change_request", "work_end", "VARCHAR(64)"),
    ("change_request", "justification", "TEXT"),
    ("change_request", "implementation_plan", "TEXT"),
    ("change_request", "backout_plan", "TEXT"),
    ("change_request", "test_plan", "TEXT"),
    ("change_request", "review_date", "VARCHAR(64)"),
    ("change_request", "approval", "VARCHAR(64)"),
    # change_task
    ("change_task", "active", "VARCHAR(8)"),
    ("change_task", "work_notes", "TEXT"),
    ("change_task", "comments", "TEXT"),
    ("change_task", "opened_at", "VARCHAR(64)"),
    ("change_task", "closed_at", "VARCHAR(64)"),
    ("change_task", "resolved_at", "VARCHAR(64)"),
    ("change_task", "due_date", "VARCHAR(64)"),
    ("change_task", "business_service", "VARCHAR(32)"),
    ("change_task", "escalation", "VARCHAR(8)"),
    ("change_task", "priority", "VARCHAR(8)"),
    ("change_task", "impact", "VARCHAR(8)"),
    ("change_task", "urgency", "VARCHAR(8)"),
    # sc_request
    ("sc_request", "active", "VARCHAR(8)"),
    ("sc_request", "work_notes", "TEXT"),
    ("sc_request", "comments", "TEXT"),
    ("sc_request", "opened_at", "VARCHAR(64)"),
    ("sc_request", "closed_at", "VARCHAR(64)"),
    ("sc_request", "resolved_at", "VARCHAR(64)"),
    ("sc_request", "due_date", "VARCHAR(64)"),
    ("sc_request", "cmdb_ci", "VARCHAR(32)"),
    ("sc_request", "business_service", "VARCHAR(32)"),
    ("sc_request", "escalation", "VARCHAR(8)"),
    ("sc_request", "request_state", "VARCHAR(64)"),
    ("sc_request", "priority", "VARCHAR(8)"),
    ("sc_request", "urgency", "VARCHAR(8)"),
    ("sc_request", "impact", "VARCHAR(8)"),
    ("sc_request", "delivery_plan", "TEXT"),
    ("sc_request", "delivery_task", "VARCHAR(256)"),
    ("sc_request", "stage", "VARCHAR(64)"),
    ("sc_request", "approval", "VARCHAR(64)"),
    ("sc_request", "opened_by", "VARCHAR(32)"),
    ("sc_request", "category", "VARCHAR(128)"),
    ("sc_request", "subcategory", "VARCHAR(128)"),
    # sc_task
    ("sc_task", "active", "VARCHAR(8)"),
    ("sc_task", "work_notes", "TEXT"),
    ("sc_task", "comments", "TEXT"),
    ("sc_task", "opened_at", "VARCHAR(64)"),
    ("sc_task", "closed_at", "VARCHAR(64)"),
    ("sc_task", "resolved_at", "VARCHAR(64)"),
    ("sc_task", "due_date", "VARCHAR(64)"),
    ("sc_task", "cmdb_ci", "VARCHAR(32)"),
    ("sc_task", "business_service", "VARCHAR(32)"),
    ("sc_task", "escalation", "VARCHAR(8)"),
    ("sc_task", "priority", "VARCHAR(8)"),
    ("sc_task", "urgency", "VARCHAR(8)"),
    ("sc_task", "impact", "VARCHAR(8)"),
    ("sc_task", "cat_item", "VARCHAR(32)"),
    ("sc_task", "request_item", "VARCHAR(32)"),
    ("sc_task", "stage", "VARCHAR(64)"),
    ("sc_task", "approval", "VARCHAR(64)"),
    # sc_cat_item (renamed from service_catalog_item)
    ("sc_cat_item", "description", "TEXT"),
    ("sc_cat_item", "category", "VARCHAR(128)"),
    ("sc_cat_item", "subcategory", "VARCHAR(128)"),
    ("sc_cat_item", "fulfillment_group", "VARCHAR(32)"),
    ("sc_cat_item", "order", "INTEGER DEFAULT 100"),
    ("sc_cat_item", "icon", "VARCHAR(256)"),
    ("sc_cat_item", "other", "JSONB DEFAULT '{}'::jsonb"),
    # sc_req_item
    ("sc_req_item", "active", "VARCHAR(8)"),
    ("sc_req_item", "work_notes", "TEXT"),
    ("sc_req_item", "comments", "TEXT"),
    ("sc_req_item", "opened_at", "VARCHAR(64)"),
    ("sc_req_item", "closed_at", "VARCHAR(64)"),
    ("sc_req_item", "resolved_at", "VARCHAR(64)"),
    ("sc_req_item", "due_date", "VARCHAR(64)"),
    ("sc_req_item", "cmdb_ci", "VARCHAR(32)"),
    ("sc_req_item", "business_service", "VARCHAR(32)"),
    ("sc_req_item", "escalation", "VARCHAR(8)"),
    ("sc_req_item", "stage", "VARCHAR(64)"),
    ("sc_req_item", "quantity", "INTEGER DEFAULT 1"),
    ("sc_req_item", "price", "VARCHAR(32)"),
    ("sc_req_item", "approval", "VARCHAR(64)"),
    ("sc_req_item", "priority", "VARCHAR(8)"),
    ("sc_req_item", "urgency", "VARCHAR(8)"),
    ("sc_req_item", "impact", "VARCHAR(8)"),
    ("sc_req_item", "opened_by", "VARCHAR(32)"),
    ("sc_req_item", "requested_for", "VARCHAR(32)"),
    ("sc_req_item", "upon_approval", "VARCHAR(32) DEFAULT 'proceed'"),
    ("sc_req_item", "upon_reject", "VARCHAR(32) DEFAULT 'cancel'"),
    ("sc_req_item", "approval_set", "VARCHAR(64)"),
    ("sc_req_item", "made_sla", "VARCHAR(8) DEFAULT 'true'"),
    ("sc_req_item", "reassignment_count", "VARCHAR(8) DEFAULT '0'"),
    ("sc_req_item", "recurring_price", "VARCHAR(32) DEFAULT '0'"),
    ("sc_req_item", "backordered", "VARCHAR(8) DEFAULT 'false'"),
    ("sc_req_item", "billable", "VARCHAR(8) DEFAULT 'false'"),
    ("sc_req_item", "knowledge", "VARCHAR(8) DEFAULT 'false'"),
    ("sc_req_item", "delivery_plan", "VARCHAR(32)"),
    ("sc_req_item", "sys_domain", "VARCHAR(64) DEFAULT 'global'"),
    ("sc_req_item", "sys_domain_path", "VARCHAR(256) DEFAULT '/'"),
    ("sc_req_item", "task_effective_number", "VARCHAR(32)"),
    # sc_cat_item_webhook — attachment to standalone sc_webhook
    ("sc_cat_item_webhook", "webhook", "VARCHAR(32)"),
    ("sc_cat_item_webhook", "payload_template", "TEXT"),
    ("sc_cat_item_webhook", "trigger_on", "VARCHAR(32)"),
    ("sc_cat_item_webhook", "active", "BOOLEAN DEFAULT TRUE"),
    ("sc_webhook_log", "attachment_id", "VARCHAR(32)"),
    # sys_user
    ("sys_user", "phone", "VARCHAR(64)"),
    ("sys_user", "mobile_phone", "VARCHAR(64)"),
    ("sys_user", "department", "VARCHAR(128)"),
    ("sys_user", "title", "VARCHAR(128)"),
    ("sys_user", "location", "VARCHAR(256)"),
    ("sys_user", "company", "VARCHAR(128)"),
    ("sys_user", "manager", "VARCHAR(32)"),
    ("sys_user", "time_zone", "VARCHAR(64)"),
    ("sys_user", "vip", "VARCHAR(8)"),
    ("sys_user", "employee_number", "VARCHAR(64)"),
    ("sys_user", "preferences", "JSONB DEFAULT '{}'::jsonb"),
    # sys_user_group
    ("sys_user_group", "type", "VARCHAR(64)"),
    ("sys_user_group", "active", "VARCHAR(8)"),
    ("sys_user_group", "email", "VARCHAR(256)"),
    ("sys_user_group", "manager", "VARCHAR(32)"),
    ("sys_user_group", "parent", "VARCHAR(32)"),
    # std_change_producer_version
    ("std_change_producer_version", "active", "VARCHAR(8)"),
    ("std_change_producer_version", "template", "TEXT"),
    ("std_change_producer_version", "category", "VARCHAR(128)"),
    ("std_change_producer_version", "instructions", "TEXT"),
    ("std_change_producer_version", "description", "TEXT"),
    # sys_attachment
    ("sys_attachment", "hash", "VARCHAR(256)"),
    ("sys_attachment", "state", "VARCHAR(32)"),
    # sys_role
    ("sys_role", "description", "TEXT"),
    ("sys_role", "suffix", "VARCHAR(64)"),
    # cmdb_rel_ci
    ("cmdb_rel_ci", "connection_strength", "VARCHAR(64)"),
]

# Tables using LifecycleMixin — widen audit columns to store usernames (ServiceNow-compatible).
AUDIT_USERNAME_TABLES = [
    "sys_user",
    "sys_user_group",
    "record_access_grant",
    "sys_comment",
    "sys_user_grmember",
    "incident",
    "problem",
    "problem_task",
    "change_request",
    "change_task",
    "cmdb_ci",
    "cmdb_rel_ci",
    "sc_request",
    "sc_req_item",
    "sc_task",
    "item_option_new",
    "item_option_new_condition",
    "sc_item_option",
    "sc_cat_item_webhook",
    "sc_webhook",
    "sc_webhook_log",
    "sys_secret",
    "sys_attachment",
]

# sys_mod_count applies to every LifecycleMixin table, which is exactly AUDIT_USERNAME_TABLES.
MOD_COUNT_COLUMN_MIGRATIONS: list[tuple[str, str, str]] = [
    (table, "sys_mod_count", "INTEGER DEFAULT 0") for table in AUDIT_USERNAME_TABLES
]
